import matplotlib.pyplot as plt
import pandas as pd

plt.rcParams["font.family"] = "sans-serif"
plt.rcParams["font.sans-serif"] = "times new roman"
plt.rcParams['lines.linewidth'] = 1.5
plt.rcParams['axes.xmargin'] = 0
plt.rcParams['axes.ymargin'] = 0
plt.rcParams['axes.autolimit_mode'] = 'round_numbers'
  
s = pd.read_csv('standard fire curve.csv')
t1 = pd.read_csv('t1.csv')
t8 = pd.read_csv('t8.csv')
t9 = pd.read_csv('t9.csv')

ax = plt.axes()     
ax.yaxis.grid(True, linestyle=':') # horizontal lines
ax.xaxis.grid(True, linestyle=':') # vertical lines
ax.xaxis.label.set_size(12)
ax.yaxis.label.set_size(12)
ax.set_xlim([0,250])
plt.plot(s['ISO 834-Time'],s['ISO 834-Temp'], linestyle='--', label='Standard fire curve', color='maroon')
plt.plot(t1['Time in Minutes'],t1['Average-Pb1'], label='T1-Pb1', color='red', linestyle=':', markevery=10, ms=4, marker='o')
plt.plot(t8['Time in Minutes'],t8['Average-Pb1'], label='T8-Pb1', color='red', linestyle='--', markevery=20, ms=4, marker='v')
plt.plot(t9['Time in Minutes'],t9['Average-Pb1'], label='T9-Pb1', color='red', linestyle='--', markevery=20, ms=4, marker='s')
plt.plot(t1['Time in Minutes'],t1['Average-Pb1-Pb2'], label='T1-Pb1-Pb2', color='C0', linestyle=':', markevery=10, ms=4, marker='d')
plt.plot(t8['Time in Minutes'],t8['Average-Pb1-Pb2'], label='T8-Pb1-Pb2', color='C0', markevery=20, ms=4, marker='x')
plt.plot(t9['Time in Minutes'],t9['Average-Pb1-Pb2'], label='T9-Pb1-Pb2', color='C0', linestyle='--', markevery=20, ms=4, marker='p')
plt.plot(t1['Time in Minutes'],t1['Average-Pb2'], label='T1-Pb2', color='C1', linestyle=':', markevery=10, ms=4, marker='+')
plt.plot(t8['Time in Minutes'],t8['Average-Pb2'], label='T8-Pb2', color='C1', markevery=20, ms=4, marker='*')
plt.plot(t9['Time in Minutes'],t9['Average-Pb2'], label='T9-Pb2', color='C1', linestyle='--', markevery=20, ms=4, marker='P')
plt.plot(t1['Time in Minutes'],t1['Average-Pb3'], label='T1-Pb3', color='C2', linestyle=':', markevery=10, ms=4, marker='X')
plt.plot(t8['Time in Minutes'],t8['Average-Pb3-Fire'], label='T8-Pb3-Fire', color='C6', markevery=20, ms=4, marker='h')
plt.plot(t8['Time in Minutes'],t8['Average-Pb3-Amb'], label='T8-Pb3-Amb', color='C7', markevery=20, ms=4, marker='D')
plt.plot(t8['Time in Minutes'],t8['Average-Pb4'], label='T8-Pb4', color='C2', linestyle='--', markevery=20, ms=4, marker='H')
plt.plot(t9['Time in Minutes'],t9['Average-Pb3'], label='T9-Pb3', color='C2', linestyle='--', markevery=20, ms=4, marker='^')
plt.plot(t1['Time in Minutes'],t1['Average-Pb3-Pb4'], label='T1-Pb3-Pb4', color='C4', linestyle=':', markevery=10, ms=4, marker='<')
plt.plot(t8['Time in Minutes'],t8['Average-Pb4-Pb5'], label='T8-Pb4-Pb5', color='C4', markevery=20, ms=4, marker='>')
plt.plot(t9['Time in Minutes'],t9['Average-Pb3-Pb4'], label='T9-Pb3-Pb4', color='C4', linestyle='--', markevery=20, ms=4, marker='8')
plt.plot(t1['Time in Minutes'],t1['Average-Pb4'], label='T1-Pb4', color='C8', linestyle=':', markevery=10, ms=4, marker='|')
plt.plot(t8['Time in Minutes'],t8['Average-Pb5'], label='T8-Pb5', color='C8', markevery=20, ms=4, marker='3')
plt.plot(t9['Time in Minutes'],t9['Average-Pb4'], label='T9-Pb4', color='C8', linestyle='--', markevery=20, ms=4, marker='4')
plt.xlabel('Time (min)', fontsize=14)
plt.ylabel('Temperature (°C)', fontsize=14)
plt.legend(fontsize=14, loc=9, bbox_to_anchor=(0.5, -0.15), ncol=3)
plt.gcf()
plt.savefig('T1vsT8vsT9-Avg-Pb.pdf', bbox_inches='tight')
plt.show()

ax = plt.axes()        
ax.yaxis.grid(True, linestyle=':') # horizontal lines
ax.xaxis.grid(True, linestyle=':') # vertical lines
ax.xaxis.label.set_size(12)
ax.yaxis.label.set_size(12)
plt.plot(t1['Time in Minutes'],t1['Stud3-Top-Fire-HF'], label='T1-Stud3-Top-Fire-HF', color='red', markevery=15, ms=4, marker='o')
plt.plot(t8['Time in Minutes'],t8['Stud3-Mid-Fire-HF'], label='T8-Stud3-Mid-Fire-HF', color='red', markevery=15, ms=4, marker='x', linestyle='--')
plt.plot(t9['Time in Minutes'],t9['Stud3-Top-Fire-HF'], label='T9-Stud3-Top-Fire-HF', color='red', markevery=15, ms=4, marker='X', linestyle='-.')
plt.plot(t1['Time in Minutes'],t1['Stud3-Top-Fire-CF'], label='T1-Stud3-Top-Fire-CF', color='C0', markevery=15, ms=4, marker='v')
plt.plot(t8['Time in Minutes'],t8['Stud3-Mid-Fire-CF'], label='T8-Stud3-Mid-Fire-CF', color='C0', markevery=15, ms=4, marker='p', linestyle='--')
plt.plot(t9['Time in Minutes'],t9['Stud3-Top-Fire-CF'], label='T9-Stud3-Top-Fire-CF', color='C0', markevery=15, ms=4, marker='h', linestyle='-.')
plt.plot(t1['Time in Minutes'],t1['Stud3-Top-Amb-HF'], label='T1-Stud3-Top-Amb-HF', color='C1', markevery=15, ms=4, marker='s')
plt.plot(t8['Time in Minutes'],t8['Stud3-Mid-Amb-HF'], label='T8-Stud3-Mid-Amb-HF', color='C1', markevery=15, ms=4, marker='+', linestyle='--')
plt.plot(t9['Time in Minutes'],t9['Stud3-Top-Amb-HF'], label='T9-Stud3-Top-Amb-HF', color='C1', markevery=15, ms=4, marker='o', linestyle='-.')
plt.plot(t1['Time in Minutes'],t1['Stud3-Top-Amb-CF'], label='T1-Stud3-Top-Amb-CF', color='C2', markevery=15, ms=4, marker='d')
plt.plot(t8['Time in Minutes'],t8['Stud3-Mid-Amb-CF'], label='T8-Stud3-Mid-Amb-CF', color='C2', markevery=15, ms=4, marker='*', linestyle='--')
plt.plot(t9['Time in Minutes'],t9['Stud3-Top-Amb-CF'], label='T9-Stud3-Top-Amb-CF', color='C2', markevery=15, ms=4, marker='>', linestyle='-.')
plt.xlabel('Time(min)', fontsize=14)
plt.ylabel('Temperature(°C)', fontsize=14)
plt.legend(fontsize=14, loc=9, bbox_to_anchor=(0.5, -0.15), ncol=2)
plt.gcf()
plt.savefig('T1vsT8vsT9-Studs.pdf', bbox_inches='tight')
plt.show()

#ax = plt.axes()        
#ax.yaxis.grid(True, linestyle=':') # horizontal lines
#ax.xaxis.grid(True, linestyle=':') # vertical lines
##ax.set_xlim([0,225])
#ax.xaxis.label.set_size(12)
#ax.yaxis.label.set_size(12)
#plt.plot(t9['Time in Minutes'],t9['Stud3-Mid-Fire-HF'], label='T9-Stud3-Mid-Fire-HF', color='red')
#plt.plot(t9['Time in Minutes'],t9['Stud3-Mid-Fire-CF'], label='T9-Stud3-Mid-Fire-CF', color='red', linestyle='--')
#plt.plot(t9['Time in Minutes'],t9['Stud3-Mid-Amb-HF'], label='T9-Stud3-Mid-Amb-HF', color='C0')
#plt.plot(t9['Time in Minutes'],t9['Stud3-Mid-Amb-CF'], label='T9-Stud3-Mid-Amb-CF', color='C0', linestyle='--')
#plt.plot(t8['Time in Minutes'],t8['Stud3-Mid-Fire-HF'], label='T8-Stud3-Mid-Fire-HF', color='C1')
#plt.plot(t8['Time in Minutes'],t8['Stud3-Mid-Fire-CF'], label='T8-Stud3-Mid-Fire-CF', color='C1', linestyle='--')
#plt.plot(t8['Time in Minutes'],t8['Stud3-Mid-Amb-HF'], label='T8-Stud3-Mid-Amb-HF', color='C2')
#plt.plot(t8['Time in Minutes'],t8['Stud3-Mid-Amb-CF'], label='T8-Stud3-Mid-Amb-CF', color='C2', linestyle='--')
#plt.plot(t6['Time in Minutes'],t6['Stud3-Mid-HF'], label='T6-Stud3-Mid-HF', color='C3')
#plt.plot(t6['Time in Minutes'],t6['Stud3-Mid-CF'], label='T6-Stud3-Mid-CF', color='C3', linestyle='--')
#plt.xlabel('Time (min)')
#plt.ylabel('Temperature (°C)')
#plt.legend(fontsize=14, loc=9, bbox_to_anchor=(0.5, -0.15), ncol=2)
#plt.gcf()
#plt.savefig('T9vsT8vsT6-Stud3-Mid-Fire-Amb.pdf', bbox_inches='tight')
#plt.show()
#
#ax = plt.axes()        
#ax.yaxis.grid(True, linestyle=':') # horizontal lines
#ax.xaxis.grid(True, linestyle=':') # vertical lines
##ax.set_xlim([0,225])
#ax.xaxis.label.set_size(12)
#ax.yaxis.label.set_size(12)
#plt.plot(t9['Time in Minutes'],t9['Stud3-Mid-Fire-HF'], label='T9-Stud3-Mid-Fire-HF', color='red')
#plt.plot(t8['Time in Minutes'],t8['Stud3-Mid-Fire-HF'], label='T8-Stud3-Mid-Fire-HF', color='red', linestyle='--')
#plt.plot(t6['Time in Minutes'],t6['Stud3-Mid-HF'], label='T6-Stud3-Mid-HF', color='red', linestyle=':')
#plt.plot(t9['Time in Minutes'],t9['Stud3-Mid-Amb-HF'], label='T9-Stud3-Mid-Amb-HF', color='C0')
#plt.plot(t8['Time in Minutes'],t8['Stud3-Mid-Amb-HF'], label='T8-Stud3-Mid-Amb-HF', color='C0', linestyle='--')
#plt.plot(t9['Time in Minutes'],t9['Stud3-Mid-Amb-CF'], label='T9-Stud3-Mid-Amb-CF', color='C0', linestyle=':')
#plt.plot(t9['Time in Minutes'],t9['Stud3-Mid-Fire-CF'], label='T9-Stud3-Mid-Fire-CF', color='C1')
#plt.plot(t8['Time in Minutes'],t8['Stud3-Mid-Fire-CF'], label='T8-Stud3-Mid-Fire-CF', color='C1', linestyle='--')
#plt.plot(t8['Time in Minutes'],t8['Stud3-Mid-Amb-CF'], label='T8-Stud3-Mid-Amb-CF', color='C1', linestyle=':')
#plt.plot(t6['Time in Minutes'],t6['Stud3-Mid-CF'], label='T6-Stud3-Mid-CF', color='C1', linestyle='-.')
#plt.xlabel('Time (min)')
#plt.ylabel('Temperature (°C)')
#plt.legend(fontsize=14, loc=9, bbox_to_anchor=(0.5, -0.15), ncol=2)
#plt.gcf()
#plt.savefig('T9vsT8vsT6-Stud3-Mid-Fire-Amb1.pdf', bbox_inches='tight')
#plt.show()

#ax = plt.axes()        
#ax.yaxis.grid(True, linestyle=':') # horizontal lines
#ax.xaxis.grid(True, linestyle=':') # vertical lines
##ax.set_xlim([0,225])
#ax.xaxis.label.set_size(12)
#ax.yaxis.label.set_size(12)
#plt.plot(t9['Time in Minutes'],t9['Stud4-Mid-Fire-HF'], label='T9-Stud4-Mid-Fire-HF', color='red', markevery=20, ms=4, marker='o')
#plt.plot(t9['Time in Minutes'],t9['Stud4-Mid-Fire-CF'], label='T9-Stud4-Mid-Fire-CF', color='C0', markevery=20, ms=4, marker='v')
#plt.plot(t9['Time in Minutes'],t9['Stud4-Mid-Amb-HF'], label='T9-Stud4-Mid-Amb-HF', color='C1', markevery=20, ms=4, marker='s')
#plt.plot(t9['Time in Minutes'],t9['Stud4-Mid-Amb-CF'], label='T9-Stud4-Mid-Amb-CF', color='C2', markevery=20, ms=4, marker='d')
#plt.plot(t8['Time in Minutes'],t8['Stud4-Mid-Fire-HF'], label='T8-Stud4-Mid-Fire-HF', color='red', linestyle='--', markevery=20, ms=4, marker='x')
#plt.plot(t8['Time in Minutes'],t8['Stud4-Mid-Fire-CF'], label='T8-Stud4-Mid-Fire-CF', color='C0', linestyle='--', markevery=20, ms=4, marker='p')
#plt.plot(t8['Time in Minutes'],t8['Stud4-Mid-Amb-HF'], label='T8-Stud4-Mid-Amb-HF', color='C1', linestyle='--', markevery=20, ms=4, marker='+')
#plt.plot(t8['Time in Minutes'],t8['Stud4-Mid-Amb-CF'], label='T8-Stud4-Mid-Amb-CF', color='C2', linestyle='--', markevery=20, ms=4, marker='*')
#plt.plot(t6['Time in Minutes'],t6['Stud4-Mid-HF'], label='T6-Stud4-Mid-HF', color='red', linestyle=':', markevery=20, ms=4, marker='1')
#plt.plot(t6['Time in Minutes'],t6['Stud4-Mid-CF'], label='T6-Stud4-Mid-CF', color='C0', linestyle=':', markevery=20, ms=4, marker='h')
#plt.xlabel('Time (min)')
#plt.ylabel('Temperature (°C)')
#plt.legend(fontsize=14, loc=9, bbox_to_anchor=(0.5, -0.15), ncol=2)
#plt.gcf()
#plt.savefig('T9vsT8vsT6-Stud4-Mid-Fire-Amb.pdf', bbox_inches='tight')
#plt.show()

#ax = plt.axes()        
#ax.yaxis.grid(True, linestyle=':') # horizontal lines
#ax.xaxis.grid(True, linestyle=':') # vertical lines
##ax.set_xlim([0,225])
#ax.xaxis.label.set_size(12)
#ax.yaxis.label.set_size(12)
#plt.plot(t9['Time in Minutes'],t9['Stud4-Mid-Fire-HF'], label='T9-Stud4-Mid-Fire-HF', color='red')
#plt.plot(t8['Time in Minutes'],t8['Stud4-Mid-Fire-HF'], label='T8-Stud4-Mid-Fire-HF', color='red', linestyle='--')
#plt.plot(t6['Time in Minutes'],t6['Stud4-Mid-HF'], label='T6-Stud4-Mid-HF', color='red', linestyle=':')
#plt.plot(t9['Time in Minutes'],t9['Stud4-Mid-Amb-HF'], label='T9-Stud4-Mid-Amb-HF', color='C0')
#plt.plot(t8['Time in Minutes'],t8['Stud4-Mid-Amb-HF'], label='T8-Stud4-Mid-Amb-HF', color='C0', linestyle='--')
#plt.plot(t9['Time in Minutes'],t9['Stud4-Mid-Amb-CF'], label='T9-Stud4-Mid-Amb-CF', color='C0', linestyle=':')
#plt.plot(t9['Time in Minutes'],t9['Stud4-Mid-Fire-CF'], label='T9-Stud4-Mid-Fire-CF', color='C1')
#plt.plot(t8['Time in Minutes'],t8['Stud4-Mid-Fire-CF'], label='T8-Stud4-Mid-Fire-CF', color='C1', linestyle='--')
#plt.plot(t8['Time in Minutes'],t8['Stud4-Mid-Amb-CF'], label='T8-Stud4-Mid-Amb-CF', color='C1', linestyle=':')
#plt.plot(t6['Time in Minutes'],t6['Stud4-Mid-CF'], label='T6-Stud4-Mid-CF', color='C1', linestyle='-.')
#plt.xlabel('Time (min)')
#plt.ylabel('Temperature (°C)')
#plt.legend(fontsize=14, loc=9, bbox_to_anchor=(0.5, -0.15), ncol=2)
#plt.gcf()
#plt.savefig('T9vsT8vsT6-Stud4-Mid-Fire-Amb1.pdf', bbox_inches='tight')
#plt.show()

#ax = plt.axes()        
#ax.yaxis.grid(True, linestyle=':') # horizontal lines
#ax.xaxis.grid(True, linestyle=':') # vertical lines
#ax.xaxis.label.set_size(12)
#ax.yaxis.label.set_size(12)
#plt.plot(t9['Time in Minutes'],t9['Stud3-Mid'], label='T9-Stud3-Mid', color='red', markevery=20, ms=4, marker='o')
#plt.plot(t9['Time in Minutes'],t9['Stud4-Mid'], label='T9-Stud4-Mid', color='red', linestyle='--', markevery=20, ms=4, marker='v')
#plt.plot(t8['Time in Minutes'],t8['Stud3-Mid'], label='T8-Stud3-Mid', color='C0', markevery=20, ms=4, marker='s')
#plt.plot(t8['Time in Minutes'],t8['Stud4-Mid'], label='T8-Stud3-Mid', color='C0', linestyle='--', markevery=20, ms=4, marker='d')
#plt.plot(t6['Time in Minutes'],t6['Stud3-Mid'], label='T6-Stud3-Mid', color='C1', markevery=20, ms=4, marker='x')
#plt.plot(t6['Time in Minutes'],t6['Stud4-Mid'], label='T6-Stud4-Mid', color='C1', linestyle='--', markevery=20, ms=4, marker='p')
#plt.xlabel('Time (min)')
#plt.ylabel('Lateral Deflection (mm)')
#plt.legend(fontsize=14, loc=9, bbox_to_anchor=(0.5, -0.15), ncol=3)
#plt.gcf()
#plt.savefig('T9vsT8vsT6-Lateral-Mid.pdf', bbox_inches='tight')
#plt.show()



